# ~/.bashrc: executed by bash(1) for non-login shells.

PS1='\[\033[01;32m\]mov@dev\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $ '
alias mvn="/app/mvnw -Dstyle.color=always -Dquarkus-log-max-startup-records=100000"
alias mvnd="mvn -Dmaven.surefire.debug=\"-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=0.0.0.0:5005 -Xnoagent -Djava.compiler=NONE\""
alias startServer="mvn compile quarkus:dev -DdebugHost=0.0.0.0"
/app/checkUpdate.sh